/*
  Symphony of War — Squad Build Calculator (P0 baseline).
  Build-first + overlay-driven. Reads window.SOW_DATA (generated by build-data.mjs).

  The home screen is the game's 3D-angled formation. Each rank is 6 rectangles; a unit is
  2 rectangles wide (column 0-4 = its left rectangle), so units in a rank must be ≥2 columns
  apart (max 3/rank). This 2-wide footprint drives cover: a non-front unit is "covered"
  (−20% dmg) when a front ally is within |Δcol| ≤ 1 (light) or ≤ 2 (heavy). Clicking a slot
  opens the ROSTER selector overlay; inside it you set the unit's class/level/affinity and
  can open the CLASS UPGRADE TREE (a detail overlay stacked above) to navigate classup/
  classdown edges and analyse requirements, costs, param_add and the stat curve.

  Conventions honoured: statically-sized overlays, scroll-preserving re-renders, event
  delegation on the roots, escape=dismiss / Confirm=commit, traits-as-data banners, and a
  grid stat table with fixed Base | Class Bonus | Total semantics.

  NOTE: stats here are the raw class-table curve + flat param_add — a first-pass sandbox
  metric. The full effective-stat assembly (level variance, affinity growth, "homegrown",
  softcaps, equipment) is a P1 item; see Progress.md.
*/
(function () {
  "use strict";

  const DATA = window.SOW_DATA || {};
  const STORAGE_KEY = "sowbc.squad";
  const SQUAD_SIZE = 15;          // 3 ranks × 5 column-positions
  const COLS = 5;                 // a unit's left-edge position 0-4 within a rank
  const RANKS = 3;
  // The game's grid: each rank is 6 rectangles; a unit is 2 rectangles wide, so its column
  // 0-4 is the left rectangle and it occupies {col, col+1}. Two units in a rank must be
  // ≥2 columns apart (no rectangle overlap) → max 3 per rank. |Δcol| is in half-tiles, which
  // is exactly what the cover/block ranges (0462) use. See COMBAT below.
  const COMBAT = DATA.combat || { coverMod: 0.8, rowMod: 0.8, coverCol: { light: 1, heavy: 2 }, block: { fullLimit: 1, halfLimit: 2, fullMult: 0, halfMult: 0.5 } };
  // leader = the front-most, most-central occupied unit
  const LEADER_ORDER = [0, 2, 4, 1, 3, 5, 7, 9, 6, 8, 10, 12, 14, 11, 13];

  const classById  = new Map((DATA.classes || []).map((c) => [c.id, c]));
  const heroById   = new Map((DATA.heroes || []).map((h) => [h.id, h]));
  const traitById  = new Map((DATA.traits || []).map((t) => [t.id, t]));
  const affById    = new Map((DATA.affinities || []).map((a) => [a.id, a]));
  const STAT_META  = DATA.statMeta || [];
  const PARAM_LABEL = DATA.paramLabel || {};

  // param_add note-tag keys → canonical class-table stat keys (02_stats_scaling.md:
  // def and armor both target the Armor param). Keys not mapped (e.g. agi) are shown raw
  // in the class detail but not folded into the 8-stat table.
  const PARAM_ADD_MAP = { mhp: "HP", atk: "Attack", mat: "Magic", def: "Armor", armor: "Armor", weapon_power: "WeaponPower", skl: "Skill" };
  const RESOURCE_LABEL = { iron: "Iron", obsidian: "Obsidian", gems: "Gems", horse: "Horse", sunstone: "Sunstone", pyrocite: "Pyrocite" };

  // ── gender availability by classup reachability from the gendered bases (15 §2a).
  // Male bases Fighter/Bowman, female bases Militia/Medic; SHARED = reachable from both.
  const _reach = (roots) => {
    const seen = new Set(), stack = roots.slice();
    while (stack.length) { const s = stack.pop(); if (seen.has(s) || !classById.has(s)) continue; seen.add(s);
      (classById.get(s).classup || []).forEach((c) => stack.push(c)); }
    return seen;
  };
  const _male = _reach(["fighter", "bowman"]), _female = _reach(["militia", "medic"]);
  // Prefer the build-time `gavail` field (build-data.mjs); fall back to the client reachability calc.
  function gavail(id) {
    const c = classById.get(id);
    if (c && c.gavail) return c.gavail;
    const m = _male.has(id), f = _female.has(id);
    return (m && f) ? "shared" : f ? "f" : m ? "m" : "any";
  }
  const GBADGE = { m: "♂", f: "♀", shared: "⚥" }, GLABEL = { m: "Male tree", f: "Female tree", shared: "Shared (both genders)", any: "" };
  // battle sprite (assets/sprites/class_<id>.png), falling back to the classcard icon
  const battleSprite = (cls) => (cls ? `assets/sprites/class_${cls.id}.png` : "");

  const lensFromGavail = (g) => (g === "f" ? "f" : g === "m" ? "m" : "all");
  // Set the class-tree lens from the unit being edited: heroes LOCK to their gender;
  // generics default from the class's gavail but stay toggleable (generic gender is ambiguous).
  function setLensForEditedUnit() {
    if (!state.ovl) { state.treeLockGender = null; return; }
    const hero = state.ovl.heroId ? heroById.get(state.ovl.heroId) : null;
    if (hero) {
      const g = hero.gender === "f" ? "f" : "m";
      state.treeLens = g; state.treeLockGender = g;
    } else {
      const cls = state.ovl.classId ? classById.get(state.ovl.classId) : null;
      state.treeLens = lensFromGavail(cls && cls.gavail); state.treeLockGender = null;
    }
  }

  // ── state ──
  const state = { squad: load(), ovl: null, treeLens: "all", treeLockGender: null };

  function makeUnit(hero) {
    return { heroId: hero.id, classId: hero.startClass || null, level: hero.level || 1, affinity: hero.affinity, homegrown: true };
  }
  function load() {
    let arr = [];
    try { arr = JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; } catch { arr = []; }
    // a slot holds a named hero (heroId) or a generic unit (classId only)
    return Array.from({ length: SQUAD_SIZE }, (_, i) => (arr[i] && (arr[i].heroId || arr[i].classId) ? arr[i] : null));
  }
  function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.squad)); }

  // ── grid geometry & placement (2-wide units, non-overlapping) ──
  const rowOf = (i) => Math.floor(i / COLS);
  const colOf = (i) => i % COLS;
  const slotOf = (rank, col) => rank * COLS + col;
  function occCols(rank) {
    const cols = [];
    for (let c = 0; c < COLS; c++) if (state.squad[slotOf(rank, c)]) cols.push(c);
    return cols;
  }
  // a free position is placeable iff no unit sits within 1 column (its 2-wide body would overlap)
  function canPlace(rank, col) {
    if (col < 0 || col >= COLS) return false;
    for (let c = col - 1; c <= col + 1; c++) if (c >= 0 && c < COLS && state.squad[slotOf(rank, c)]) return false;
    return true;
  }
  // resolve any legacy/overlapping squad: keep the left-most units, drop any within 1 column
  function normalizeSquad() {
    let changed = false;
    for (let r = 0; r < RANKS; r++) {
      let last = -9;
      for (let c = 0; c < COLS; c++) {
        const i = slotOf(r, c);
        if (!state.squad[i]) continue;
        if (c - last < 2) { state.squad[i] = null; changed = true; }
        else last = c;
      }
    }
    if (changed) persist();
  }
  const leaderSlot = () => { for (const i of LEADER_ORDER) if (state.squad[i]) return i; return 0; };

  // ── cover / block / row-bypass engine (0462) ──
  // ability accessors: a unit's cover/block flags come from its class (generic or hero's class),
  // falling back to the hero's own class_id flags when the hero keeps an off-tree class.
  function unitAbil(u) {
    const c = unitClass(u); if (c && (c.cover || c.block)) return c;
    const h = unitHero(u); return h || {};
  }
  const canCoverLight = (u) => !!unitAbil(u).cover?.light;
  const canCoverHeavy = (u) => !!unitAbil(u).cover?.heavy;
  const canBlockLight = (u) => !!unitAbil(u).block?.light;
  const canBlockHeavy = (u) => !!unitAbil(u).block?.heavy;

  // cover status of the unit at slot i: covered (dmg ×coverMod) if an ally in a rank in front
  // is within |Δcol| ≤ 1 (light coverer) or ≤ 2 (heavy coverer). Front rank (row 0) is never covered.
  function coverOf(i) {
    const u = state.squad[i]; if (!u) return null;
    const row = rowOf(i), col = colOf(i);
    if (row === 0) return { covered: false, heavy: false, light: false, coverers: [] };
    let heavy = false, light = false; const coverers = [];
    for (let r = 0; r < row; r++) for (let c = 0; c < COLS; c++) {
      const j = slotOf(r, c), a = state.squad[j]; if (!a) continue;
      const dc = Math.abs(c - col);
      const h = canCoverHeavy(a) && dc <= COMBAT.coverCol.heavy;
      const l = canCoverLight(a) && dc <= COMBAT.coverCol.light;
      if (h || l) { coverers.push(j); heavy = heavy || h; light = light || l; }
    }
    return { covered: heavy || light, heavy, light, coverers };
  }
  // slots that the unit at i (as a coverer) protects — for the on-hover highlight
  function coversFrom(i) {
    const u = state.squad[i]; if (!u) return [];
    const row = rowOf(i), col = colOf(i);
    const range = canCoverHeavy(u) ? COMBAT.coverCol.heavy : canCoverLight(u) ? COMBAT.coverCol.light : -1;
    if (range < 0) return [];
    const out = [];
    for (let r = row + 1; r < RANKS; r++) for (let c = 0; c < COLS; c++) {
      const j = slotOf(r, c); if (state.squad[j] && Math.abs(c - col) <= range) out.push(j);
    }
    return out;
  }
  // occupied ranks in front (row-bypass ×rowMod^this)
  function rowsInFront(i) {
    const row = rowOf(i); let n = 0;
    for (let r = 0; r < row; r++) if (occCols(r).length) n++;
    return n;
  }
  // targeting-rate multiplier from blockers in front (0462 blocked_by_*): full block within
  // fullLimit col → ×0; half block within halfLimit → ×halfMult^(halfLimit−Δ+1); stacks.
  function blockOf(i) {
    const u = state.squad[i]; if (!u) return 1;
    const row = rowOf(i), col = colOf(i); let v = 1;
    for (let r = 0; r < row; r++) for (let c = 0; c < COLS; c++) {
      const a = state.squad[slotOf(r, c)]; if (!a) continue;
      const dc = Math.abs(c - col);
      for (const heavy of [true, false]) {
        const can = heavy ? canBlockHeavy(a) : canBlockLight(a); if (!can) continue;
        if (dc <= COMBAT.block.fullLimit) v = Math.min(v, COMBAT.block.fullMult);
        else if (dc <= COMBAT.block.halfLimit) v *= Math.pow(COMBAT.block.halfMult, COMBAT.block.halfLimit - dc + 1);
      }
    }
    return v;
  }
  // full incoming-damage multiplier from position alone (cover × row-bypass)
  function damageTakenMod(i) {
    const cov = coverOf(i);
    return (cov && cov.covered ? COMBAT.coverMod : 1) * Math.pow(COMBAT.rowMod, rowsInFront(i));
  }

  // ── html helpers ──
  const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  function textColorFor(hex) {
    const m = /^#?([0-9a-f]{6})$/i.exec(String(hex || "")); if (!m) return "#fff";
    const n = parseInt(m[1], 16), r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255 > 0.6 ? "#111" : "#fff";
  }
  const affIcon = (id) => { const a = affById.get(id); return a ? a.icon : null; };

  // ── stat math ──
  // Piecewise-linear interpolation of the class table (L1/L20/L50), extrapolated past 50
  // with the per-level growth rate.
  function statAt(cls, key, lvl) {
    const a = Number(cls.statsL1?.[key] || 0), b = Number(cls.statsL20?.[key] || 0), c = Number(cls.statsL50?.[key] || 0);
    if (lvl <= 1) return a;
    if (lvl <= 20) return a + (b - a) * (lvl - 1) / 19;
    if (lvl <= 50) return b + (c - b) * (lvl - 20) / 30;
    return c + (Number(cls.growth?.[key] || 0)) * (lvl - 50);
  }
  function foldParamAdd(cls) {
    const out = {};
    for (const [k, v] of Object.entries(cls.paramAdd || {})) {
      const sk = PARAM_ADD_MAP[k]; if (!sk) continue;
      out[sk] = (out[sk] || 0) + Number(v || 0);
    }
    return out;
  }
  // Full per-stat readout for a class at a level: {base, bonus, total, capped} per stat key.
  function statLines(cls, lvl) {
    const bonus = foldParamAdd(cls);
    const maxBonusAbs = Math.max(0, ...Object.values(bonus).map((v) => Math.abs(v)));
    return STAT_META.map((meta) => {
      const base = Math.round(statAt(cls, meta.key, lvl));
      const add = Math.round(bonus[meta.key] || 0);
      const raw = base + add;
      const capped = meta.cap != null && raw > meta.cap;
      return { meta, base, add, total: capped ? meta.cap : raw, capped, defining: add !== 0 && Math.abs(add) === maxBonusAbs };
    });
  }

  function statTableHTML(cls, lvl) {
    if (!cls) return `<p class="muted">No class stats (off-tree special unit).</p>`;
    const rows = statLines(cls, lvl).map((s) => {
      if (!s.base && !s.add) return "";
      const hl = s.add ? (s.defining ? " hl-high" : " hl-med") : "";
      const cls2 = s.add > 0 ? " pos" : s.add < 0 ? " neg" : "";
      const disp = s.add > 0 ? "+" + s.add : s.add < 0 ? String(s.add) : "—";
      return `<div class="stat-row${hl}${s.capped ? " capped" : ""}">
        <span class="stat-key">${s.meta.icon ? `<img src="${esc(s.meta.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(s.meta.label)}</span>
        <span class="stat-base">${s.base}</span>
        <span class="stat-src stat-val${cls2}">${disp}</span>
        <span class="stat-total">${s.total}</span>
      </div>`;
    }).join("");
    return `<div class="stat-grid">
      <div class="stat-header"><span>Stat</span><span>Base</span><span>Class</span><span>Total</span></div>
      ${rows}</div>`;
  }

  // ── unit helpers ──
  const unitClass = (u) => (u && u.classId ? classById.get(u.classId) : null);
  const unitHero  = (u) => (u ? heroById.get(u.heroId) : null);
  // grid sprite: the hero's own sprite, else the class sprite (generic soldier), else null
  const unitSprite = (u) => { const h = unitHero(u); if (h?.sprite) return h.sprite; const c = unitClass(u); return c?.sprite || null; };
  function unitCost(u) { const c = unitClass(u); const raw = c ? Number(c.capacityCost) : 100; return Math.max(1, Math.round((raw || 100) / 10)); }
  function unitStatTotal(u, key) { const c = unitClass(u); if (!c) return 0; const s = statLines(c, u.level).find((x) => x.meta.key === key); return s ? s.total : 0; }

  // ── squad summary (capacity + aggregate power) ──
  function squadSummaryHTML() {
    const placed = state.squad.filter(Boolean);
    if (!placed.length) return `<p class="muted">Click a formation slot to add a unit from the roster.</p>`;
    const leader = state.squad[leaderSlot()];
    const leaderLdr = leader ? unitStatTotal(leader, "Leadership") : 0;
    const capacity = Math.max(30, leaderLdr);
    const used = placed.reduce((n, u) => n + unitCost(u), 0);
    const over = used > capacity;
    const pct = Math.min(100, Math.round((used / capacity) * 100));

    const AGG = ["HP", "Attack", "Magic", "Skill", "Armor", "WeaponPower"];
    const rows = AGG.map((key) => {
      const meta = STAT_META.find((m) => m.key === key);
      const total = placed.reduce((n, u) => n + unitStatTotal(u, key), 0);
      return `<div class="stat-row two-col">
        <span class="stat-key">${meta?.icon ? `<img src="${esc(meta.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(meta?.label || key)}</span>
        <span class="stat-total">${total}</span></div>`;
    }).join("");

    return `
      <div class="capacity-bar ${over ? "over" : ""}">
        <div class="cap-track"><div class="cap-fill" style="width:${pct}%"></div></div>
        <div class="cap-label">Capacity <b>${used} / ${capacity}</b> ${over ? '<span class="locked-note">— over capacity!</span>' : ""}
          · leader Leadership <b>${leaderLdr || "—"}</b>${leader ? "" : " (no units placed)"}</div>
      </div>
      <div class="stat-grid">
        <div class="stat-header two-col" style="grid-template-columns:1fr 62px"><span>Squad power</span><span>Σ</span></div>
        ${rows}
      </div>`;
  }

  // ── trait banners (association channel) ──
  function traitBanner(t) {
    if (!t) return "";
    const color = t.color || "var(--surface2)";
    return `<div class="trait-banner" data-action="nav-trait" data-trait="${esc(t.id)}"
      style="--aff-color:${esc(color)};--aff-text:${textColorFor(color)}" title="${esc(t.name)}">
      ${t.icon ? `<span class="trait-banner-icon"><img src="${esc(t.icon)}" alt="" onerror="this.style.visibility='hidden'"></span>` : ""}
      <span class="trait-banner-label">${esc(t.name)}</span></div>`;
  }
  function classTraitsHTML(cls) {
    if (!cls) return "";
    const ts = (cls.traits || []).map((id) => traitById.get(id)).filter(Boolean);
    return ts.length ? `<div class="primary-traits">${ts.map(traitBanner).join("")}</div>` : "";
  }

  // ── cross-reference matrix (traits × units) — shown in the Composition overlay ──
  function xrefMatrixHTML() {
    const units = state.squad.map((u, i) => (u && unitClass(u) ? { u, i, cls: unitClass(u), hero: unitHero(u) } : null)).filter(Boolean);
    if (units.length < 1) return `<p class="muted">Add units to the squad to see shared traits.</p>`;
    const count = new Map();
    for (const { cls } of units) for (const t of cls.traits || []) count.set(t, (count.get(t) || 0) + 1);
    const cols = [...count.keys()].map((id) => traitById.get(id)).filter(Boolean)
      .sort((a, b) => (count.get(b.id) - count.get(a.id)) || a.name.localeCompare(b.name));
    if (!cols.length) return `<p class="muted">No shared traits among the placed units.</p>`;
    const colHead = (t) => `<th class="xref-colhead"><div class="xref-col" data-action="nav-trait" data-trait="${esc(t.id)}"
        style="--aff-color:${esc(t.color)};--aff-text:${textColorFor(t.color)}">
        ${t.icon ? `<img class="xref-col-icon" src="${esc(t.icon)}" alt="" onerror="this.style.visibility='hidden'">` : ""}
        <span class="xref-col-name">${esc(t.name)}</span></div></th>`;
    const rows = units.map(({ cls, hero, i }) => {
      const set = new Set(cls.traits || []);
      const label = `${hero ? hero.name : cls.name} · ${cls.name}`;
      return `<tr><th class="xref-rowhead" data-action="nav-class" data-class="${esc(cls.id)}" title="Slot ${i + 1}">${esc(label)}</th>
        ${cols.map((t) => `<td class="${set.has(t.id) ? "xref-on" : ""}">${set.has(t.id) ? "●" : ""}</td>`).join("")}</tr>`;
    }).join("");
    const shared = `<tr class="xref-shared"><th class="xref-rowhead">Shared</th>
      ${cols.map((t) => { const n = count.get(t.id) || 0; return `<td class="${n >= 2 ? "xref-sh" : ""}">${n}</td>`; }).join("")}</tr>`;
    return `
      <div class="xref-wrap"><table class="squad-xref">
        <thead><tr><th class="xref-corner"></th>${cols.map(colHead).join("")}</tr></thead>
        <tbody>${rows}${shared}</tbody></table></div>
      <div class="xref-legend"><span><b class="xref-on">●</b> unit has trait</span><span><b class="xref-sh">n</b> shared by n units</span></div>`;
  }
  // Composition coverage now lives behind an overlay (opened from the header)
  function openXref() {
    const root = document.getElementById("detail-overlay-root");
    root.innerHTML = `
      <div class="overlay-panel detail-panel" role="dialog" aria-modal="true">
        <div class="overlay-header"><h2>Composition coverage</h2><button class="overlay-close" data-action="close-detail" aria-label="Close">&times;</button></div>
        <div class="overlay-body"><div class="ovl-center"><div class="ovl-center-scroll detail-main">${xrefMatrixHTML()}</div></div></div>
        <div class="overlay-footer"><button class="ghost" data-action="close-detail">Close</button></div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
    root.querySelector(".detail-main").scrollTop = 0;
  }

  // ═══ BUILD VIEW (home) — the game's 3D-angled formation grid ═══
  // sowgrid.png (GRID.width×GRID.height) is a right-skewed 3-rank parallelogram: front
  // rank on the right (enemy-facing), the 5 columns stepping down the slant. Each slot is
  // absolutely positioned at its foot-origin (GRID.origins[i]) and holds the unit's sprite,
  // anchored bottom-center, painted back-to-front so ranks overlap like the battle view.
  const GRID = DATA.grid || { width: 431, height: 95, origins: [] };

  const pctPos = (i) => {
    const [ox, oy] = GRID.origins[i] || [0, 0];
    return { left: ((ox / GRID.width) * 100).toFixed(2), top: ((oy / GRID.height) * 100).toFixed(2), oy };
  };
  function slotHTML(u, i, isLeader) {
    const { left, top, oy } = pctPos(i);
    const z = Math.round(oy) + (2 - rowOf(i));
    const style = `left:${left}%;top:${top}%;z-index:${z}`;
    if (!u) {
      return `<button class="grid-slot empty ${isLeader ? "leader" : ""}" style="${style}"
        data-action="open-slot" data-slot="${i}" aria-label="Slot ${i + 1} — empty">
        <span class="tile-mark">+</span></button>`;
    }
    const hero = unitHero(u), cls = unitClass(u), sprite = unitSprite(u);
    const name = hero ? hero.name : (cls ? cls.name : "?");
    const cov = coverOf(i), rif = rowsInFront(i), blk = blockOf(i);
    const dm = Math.round(damageTakenMod(i) * 100);
    const parts = [`${name}${cls ? " · " + cls.name : ""} · L${u.level}`,
      cov.covered ? `covered ${cov.heavy ? "(heavy)" : "(light)"} ×${COMBAT.coverMod}` : (rowOf(i) === 0 ? "front rank — uncoverable" : "not covered"),
      rif ? `row-bypass ×${COMBAT.rowMod}^${rif}` : null,
      blk < 1 ? `blocked: targeting ×${blk.toFixed(2)}` : null,
      `incoming damage ≈ ${dm}%`].filter(Boolean);
    const klass = ["grid-slot filled", isLeader ? "leader" : "", cov.covered ? "is-covered" : ""].filter(Boolean).join(" ");
    const covers = coversFrom(i);   // slots this unit protects (drives the hover highlight)
    return `<button class="${klass}" style="${style}"
      data-action="open-slot" data-slot="${i}" data-covers="${covers.join(",")}" title="${esc(parts.join(" · "))}" aria-label="${esc(parts.join(". "))}">
      ${sprite ? `<img class="grid-sprite" src="${esc(sprite)}" alt="${esc(name)}" onerror="this.style.display='none'">`
               : `<span class="tile-mark">${esc(name[0] || "?")}</span>`}
      <span class="grid-tag">${affIcon(u.affinity) ? `<img src="${esc(affIcon(u.affinity))}" alt="" onerror="this.style.display='none'">` : ""}<span class="gt-name">${esc(name)}</span> <em>L${u.level}</em></span>
    </button>`;
  }
  function formationStageHTML() {
    const lead = leaderSlot();
    let slots = "";
    for (let r = 0; r < RANKS; r++) {
      for (let c = 0; c < COLS; c++) {
        const i = slotOf(r, c);
        if (state.squad[i]) slots += slotHTML(state.squad[i], i, i === lead);       // occupied unit
        else if (canPlace(r, c)) slots += slotHTML(null, i, i === lead);            // free placement tile
        // else: blocked by an adjacent unit's 2-wide body → render nothing
      }
    }
    return `<div class="battlefield">
      <div class="formation-stage" style="aspect-ratio:${GRID.width} / ${GRID.height}">
        <img class="grid-bg" src="assets/grid/sowgrid.png" alt="Formation grid" onerror="this.style.display='none'">
        ${slots}
      </div>
    </div>`;
  }
  function renderApp() {
    const app = document.getElementById("app");
    const prevMain = app.querySelector(".planning-main");
    const prevScroll = prevMain ? prevMain.scrollTop : 0;

    app.innerHTML = `
      <header class="app-header">
        <div><h1>Symphony of War — Squad Builder</h1><div class="tagline">Formation sandbox · class upgrade-tree analysis</div></div>
        <div class="header-actions">
          <button class="ghost" data-action="open-xref">Composition ▸</button>
          <button class="ghost" data-action="clear">Clear</button>
        </div>
      </header>
      <main class="planning-main">
        <section class="formation-wrap">
          <h2>Formation</h2>
          ${formationStageHTML()}
        </section>
        <section class="squad-summary"><h2>Squad summary</h2>${squadSummaryHTML()}</section>
      </main>`;

    const newMain = app.querySelector(".planning-main");
    if (newMain) newMain.scrollTop = prevScroll;
  }

  // ═══ ROSTER SELECTOR OVERLAY (#overlay-root) ═══
  function openOverlay(slotIndex) {
    const existing = state.squad[slotIndex];
    state.ovl = existing
      ? { slotIndex, heroId: existing.heroId || null, classId: existing.classId, level: existing.level, affinity: existing.affinity, homegrown: existing.homegrown, generic: !existing.heroId && !!existing.classId, search: "" }
      : { slotIndex, heroId: null, classId: null, level: 1, affinity: null, homegrown: true, generic: false, search: "" };
    const root = document.getElementById("overlay-root");
    root.innerHTML = `
      <div class="overlay-panel" role="dialog" aria-modal="true">
        <div class="overlay-header">
          <h2>Assign unit — slot ${slotIndex + 1}${slotIndex === leaderSlot() ? " (leader)" : ""}</h2>
          <button class="overlay-close" data-action="cancel" aria-label="Close">&times;</button>
        </div>
        <div class="overlay-body">
          <div class="ovl-info"><div class="ovl-left"></div><div class="ovl-right"></div></div>
          <div class="ovl-center">
            <div class="ovl-center-search"><input class="ovl-search" type="search" placeholder="Search heroes…" /></div>
            <div class="ovl-center-scroll"><div class="ovl-grid"></div></div>
          </div>
        </div>
        <div class="overlay-footer">
          ${existing ? '<button class="ghost danger" data-action="remove">Remove unit</button>' : ""}
          <button class="ghost" data-action="cancel">Cancel</button>
          <button data-action="confirm">Confirm</button>
        </div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
    refreshOverlay();
    const input = root.querySelector(".ovl-search"); if (input) input.focus();
  }

  const SCROLLERS = [".ovl-center-scroll", ".ovl-info", ".ovl-left", ".ovl-right-body"];
  function refreshOverlay() {
    const panel = document.querySelector("#overlay-root .overlay-panel");
    if (!panel || !state.ovl) return;
    const saved = SCROLLERS.map((s) => { const el = panel.querySelector(s); return el ? el.scrollTop : 0; });

    const q = state.ovl.search.trim().toLowerCase();
    const heroes = (DATA.heroes || []).filter((h) => !q || h.name.toLowerCase().includes(q));
    // first card = a generic (unnamed) unit; you set its class via the upgrade tree.
    const genericCard = `<div class="ovl-card generic ${state.ovl.generic ? "selected" : ""}" data-action="pick-generic" title="Generic unit">
        <span class="oc-generic">＋</span><span class="oc-name">Generic unit</span></div>`;
    panel.querySelector(".ovl-grid").innerHTML = genericCard + (heroes.length ? heroes.map((h) => {
      const cls = h.startClass ? classById.get(h.startClass) : null;
      const art = h.sprite || h.portrait || cls?.sprite || cls?.icon || "";
      return `<div class="ovl-card ${h.id === state.ovl.heroId ? "selected" : ""}" data-action="pick" data-hero="${esc(h.id)}" title="${esc(h.name)}">
        ${affIcon(h.affinity) ? `<img class="oc-aff" src="${esc(affIcon(h.affinity))}" alt="" onerror="this.style.display='none'">` : ""}
        ${art ? `<img src="${esc(art)}" alt="" onerror="this.style.visibility='hidden'">` : `<span>${esc(h.name[0])}</span>`}
        <span class="oc-name">${esc(h.name)}</span></div>`;
    }).join("") : `<p class="muted">No matching heroes.</p>`);

    const hero = state.ovl.heroId ? heroById.get(state.ovl.heroId) : null;
    const cls = state.ovl.classId ? classById.get(state.ovl.classId) : null;
    const editing = hero || (state.ovl.generic && cls);

    // left: the unit's stat table at the chosen level
    panel.querySelector(".ovl-left").innerHTML = `<h3>Stats — L${state.ovl.level}</h3>` +
      (editing ? statTableHTML(cls, state.ovl.level) : `<p class="muted">Pick a hero or a generic unit.</p>`);

    // right: identity + editor controls
    panel.querySelector(".ovl-right").innerHTML = editing ? renderEditor(hero, cls) :
      `<div class="ovl-right-top"><h3>Details</h3></div><div class="ovl-right-body"><p class="muted">Select a hero or a generic unit to configure.</p></div>`;

    SCROLLERS.forEach((s, i) => { const el = panel.querySelector(s); if (el) el.scrollTop = saved[i]; });
  }

  function renderEditor(hero, cls) {
    const name = hero ? hero.name : "Generic unit";
    const locked = hero ? hero.locked : false;
    const innate = ((hero && hero.innateTraits) || []).map((id) => `<span class="req-chip">${esc(id)}</span>`).join(" ");
    const affChips = (DATA.affinities || []).map((a) => `
      <span class="aff-chip ${a.id === state.ovl.affinity ? "on" : ""}" data-action="set-aff" data-aff="${esc(a.id)}" style="--aff-color:${esc(a.color)}">
        <img src="${esc(a.icon)}" alt="" onerror="this.style.display='none'">${esc(a.name)}</span>`).join("");
    const subtitle = cls ? cls.name + " · T" + cls.tier : (hero ? "off-tree special class" : "choose a class");
    return `
      <div class="ovl-right-top">
        <h3>${esc(name)}</h3>
        <p class="muted">${esc(subtitle)}${hero && hero.customTree ? " · custom tree" : ""}${hero ? "" : " · generic"}</p>
      </div>
      <div class="ovl-right-body">
        ${classTraitsHTML(cls)}
        <div class="editor-row"><label>Level</label>
          <div class="level-control">
            <input type="range" class="lv-range" min="1" max="99" value="${state.ovl.level}">
            <input type="number" class="lv-num" min="1" max="99" value="${state.ovl.level}">
          </div></div>
        <div class="editor-row"><label>Affinity</label><div class="aff-picker">${affChips}</div></div>
        <div class="editor-row"><label>Class</label>
          ${locked
            ? `<span class="locked-note">Class locked (story unit)</span>`
            : `<button data-action="open-tree" data-class="${esc(cls ? cls.id : "fighter")}">View / change class tree ▸</button>`}
        </div>
        ${innate ? `<div class="editor-row"><label>Innate traits</label>${innate}</div>` : ""}
        <p class="muted">${hero ? "Affinity is changeable in-game; heroes start with the affinity shown." : "Generic units take the class and affinity you set here."}</p>
      </div>`;
  }

  function closeOverlay(commit) {
    if (!state.ovl) return;
    if (commit && (state.ovl.heroId || (state.ovl.generic && state.ovl.classId))) {
      state.squad[state.ovl.slotIndex] = { heroId: state.ovl.heroId || null, classId: state.ovl.classId, level: state.ovl.level, affinity: state.ovl.affinity, homegrown: state.ovl.homegrown };
      persist();
    }
    state.ovl = null;
    const root = document.getElementById("overlay-root");
    root.classList.add("hidden"); root.setAttribute("aria-hidden", "true"); root.innerHTML = "";
    renderApp();
  }
  function removeUnit() {
    if (!state.ovl) return;
    state.squad[state.ovl.slotIndex] = null; persist();
    state.ovl = null;
    const root = document.getElementById("overlay-root");
    root.classList.add("hidden"); root.setAttribute("aria-hidden", "true"); root.innerHTML = "";
    renderApp();
  }

  // ═══ CLASS UPGRADE TREE DETAIL (#detail-overlay-root) ═══
  // `editing` = opened from the roster editor, so an "Assign to unit" action is offered.
  function openClassDetail(symbol, editing) {
    const cls = classById.get(symbol); if (!cls) return;
    if (!editing) state.treeLockGender = null;   // browsing from the main app is unlocked
    state.detailClass = cls.id; state.detailEditing = editing;   // remembered so the gender lens can re-render
    const root = document.getElementById("detail-overlay-root");
    root.innerHTML = `
      <div class="overlay-panel detail-panel" role="dialog" aria-modal="true">
        <div class="overlay-header">
          <h2>${esc(cls.name)} — upgrade tree</h2>
          <button class="overlay-close" data-action="close-detail" aria-label="Close">&times;</button>
        </div>
        <div class="overlay-body"><div class="ovl-center"><div class="ovl-center-scroll detail-main">${classDetailInner(cls, editing)}</div></div></div>
        <div class="overlay-footer">
          ${editing && !isLocked() ? `<button data-action="assign-class" data-class="${esc(cls.id)}">Assign ${esc(cls.name)} to unit</button>` : ""}
          <button class="ghost" data-action="close-detail">Close</button>
        </div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
    root.querySelector(".detail-main").scrollTop = 0;
  }
  const isLocked = () => { const h = state.ovl && state.ovl.heroId ? heroById.get(state.ovl.heroId) : null; return h ? h.locked : false; };

  // lens: which genders' classes are shown. 'all' shows everything; 'm'/'f' hide the other
  // gender's exclusive classes (shared classes always show) — mirrors the class-history rule (15 §2a).
  const lensAllows = (id) => { const g = gavail(id); return state.treeLens === "all" || g === "shared" || g === "any" || g === state.treeLens; };
  const gBadge = (id) => { const g = gavail(id); return GBADGE[g] ? `<span class="gbadge ${g}" title="${GLABEL[g]}">${GBADGE[g]}</span>` : ""; };

  // a clickable class node card for the demote/promote columns
  function treeNode(symbol, showEntry) {
    const c = classById.get(symbol); if (!c) return "";
    const req = Object.entries(c.paramReq || {}).map(([k, v]) => `<span class="tn-req stat">${esc(PARAM_LABEL[k] || k)}≥${v}</span>`).join("");
    const cost = Object.entries(c.resourceCost || {}).map(([k, v]) => `<span class="tn-req">${esc(RESOURCE_LABEL[k] || k)}×${v}</span>`).join("");
    return `<div class="tree-node" data-action="nav-class" data-class="${esc(c.id)}" title="${esc(c.name)}">
      <span class="tn-tier">T${c.tier}</span>${gBadge(c.id)}
      <img src="${esc(battleSprite(c))}" alt="" onerror="this.onerror=null;this.src='${esc(c.icon || "")}'">
      <div class="tn-name">${esc(c.name)}</div>
      ${showEntry && (req || cost) ? `<div class="tn-reqs">${req}${cost}</div>` : ""}
    </div>`;
  }
  function lensBar() {
    if (state.treeLockGender) {   // locked to a hero's gender — no toggle
      return `<div class="tree-lens locked"><span class="lens-locked">${state.treeLockGender === "f" ? "♀ Female" : "♂ Male"} — locked to this unit's gender</span></div>`;
    }
    const b = (l, txt) => `<button class="${state.treeLens === l ? "on" : ""}" data-action="tree-lens" data-lens="${l}">${txt}</button>`;
    return `<div class="tree-lens">${b("all", "All")}${b("m", "♂ Male")}${b("f", "♀ Female")}</div>`;
  }

  function classDetailInner(cls, editing) {
    const g = gavail(cls.id);
    const req = Object.entries(cls.paramReq || {}).map(([k, v]) => `<span class="req-chip stat">${esc(PARAM_LABEL[k] || "param " + k)} ≥ ${v}</span>`).join(" ") || `<span class="req-none">No stat gate</span>`;
    const cost = Object.entries(cls.resourceCost || {}).map(([k, v]) => `<span class="req-chip">${esc(RESOURCE_LABEL[k] || k)} ×${v}</span>`).join(" ") || `<span class="req-none">Free</span>`;
    const padd = Object.entries(cls.paramAdd || {}).map(([k, v]) => `<span class="req-chip">${esc(k)} ${v > 0 ? "+" : ""}${v}</span>`).join(" ") || `<span class="req-none">None</span>`;

    const upAll = cls.classup || [], downAll = cls.classdown || [];
    const up = upAll.filter(lensAllows), down = downAll.filter(lensAllows);
    const downHidden = downAll.length - down.length;
    const upHTML = up.map((s) => treeNode(s, true)).join("") || `<div class="tree-empty">Top of its line — no promotions</div>`;
    const downHTML = down.map((s) => treeNode(s, false)).join("") ||
      `<div class="tree-empty">${downAll.length ? "No same-gender demote (base for this gender)" : "Base class — nothing to demote to"}</div>`;
    const crossNote = (downHidden > 0 && state.treeLens !== "all")
      ? `<div class="tree-cross">${downHidden} cross-gender base hidden — a unit reverts only along its own history (15 §2a)</div>` : "";

    return `
      ${lensBar()}
      <div class="tree-explorer">
        <div class="tree-col demote"><div class="tcol-h">◀ Demote to</div>${downHTML}${crossNote}</div>
        <div class="tree-col center">
          <div class="class-head center-card">
            <img class="ch-sprite" src="${esc(battleSprite(cls))}" alt="" onerror="this.onerror=null;this.src='${esc(cls.icon || "")}'">
            <div>
              <span class="ch-tier">Tier ${cls.tier}</span>${gBadge(cls.id)}
              <div class="ch-meta">${esc(GLABEL[g] || "any gender")} · ${esc(cls.archetype.replace(/_/g, " "))} · range ${esc(cls.combatRange)} · mastery ${cls.cxpLimit} CXP</div>
              <p>${esc(cls.description || "")}</p>
              ${classTraitsHTML(cls)}
            </div>
          </div>
          <div class="req-block">
            <div class="req-card"><h4>To become this class</h4>${req}<br>${cost}</div>
            <div class="req-card"><h4>Flat class bonus (param_add)</h4>${padd}</div>
          </div>
          <h3>Stat curve (raw class table)</h3>
          ${statCurveHTML(cls)}
        </div>
        <div class="tree-col promote"><div class="tcol-h">Promote to ▶</div>${upHTML}</div>
      </div>
      <p class="muted">Class-up needs the source's mastery bar full + tech tier unlocked. Demotion follows the unit's actual class history, so shared classes can't bridge genders (15 §2a). Stats are the raw class-table curve.</p>`;
  }
  function statCurveHTML(cls) {
    const keys = ["HP", "Attack", "Magic", "Skill", "Armor", "WeaponPower", "Leadership"];
    const rows = keys.map((k) => {
      const meta = STAT_META.find((m) => m.key === k);
      const l1 = Math.round(statAt(cls, k, 1)), l50 = Math.round(statAt(cls, k, 50)), g = (cls.growth?.[k] || 0);
      if (!l1 && !l50 && !g) return "";
      return `<div class="stat-row"><span class="stat-key">${meta?.icon ? `<img src="${esc(meta.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(meta?.label || k)}</span>
        <span class="stat-base">${l1}</span><span class="stat-src">${l50}</span><span class="stat-total">${g}/lv</span></div>`;
    }).join("");
    return `<div class="stat-grid"><div class="stat-header"><span>Stat</span><span>L1</span><span>L50</span><span>Growth</span></div>${rows}</div>`;
  }
  function closeDetail() {
    const root = document.getElementById("detail-overlay-root");
    root.classList.add("hidden"); root.setAttribute("aria-hidden", "true"); root.innerHTML = "";
  }

  // ═══ EVENT DELEGATION ═══
  function onAppClick(e) {
    const el = e.target.closest("[data-action]"); if (!el) return;
    switch (el.dataset.action) {
      case "open-slot": openOverlay(Number(el.dataset.slot)); break;
      case "open-xref": openXref(); break;
      case "clear": if (state.squad.some(Boolean)) { state.squad = state.squad.map(() => null); persist(); renderApp(); } break;
      case "nav-trait": openTraitDetail(el.dataset.trait); break;
      case "nav-class": openClassDetail(el.dataset.class, false); break;
    }
  }
  function onOverlayClick(e) {
    const el = e.target.closest("[data-action]");
    if (!el) { if (e.target.id === "overlay-root") closeOverlay(false); return; }
    switch (el.dataset.action) {
      case "pick": {
        const id = el.dataset.hero;
        if (state.ovl.heroId === id) { state.ovl.heroId = null; }
        else { const h = heroById.get(id); state.ovl.heroId = id; state.ovl.generic = false; state.ovl.classId = h.startClass || null; state.ovl.level = h.level || 1; state.ovl.affinity = h.affinity; state.ovl.homegrown = true; }
        refreshOverlay(); break;
      }
      case "pick-generic": {
        if (state.ovl.generic) { state.ovl.generic = false; state.ovl.classId = null; }
        else { state.ovl.generic = true; state.ovl.heroId = null; if (!state.ovl.classId) state.ovl.classId = "soldier"; if (!state.ovl.affinity) state.ovl.affinity = "fire"; state.ovl.level = state.ovl.level || 1; state.ovl.homegrown = true; }
        refreshOverlay(); break;
      }
      case "set-aff": state.ovl.affinity = el.dataset.aff; refreshOverlay(); break;
      case "open-tree": setLensForEditedUnit(); openClassDetail(el.dataset.class, true); break;
      case "remove": removeUnit(); break;
      case "cancel": closeOverlay(false); break;
      case "confirm": closeOverlay(true); break;
      case "nav-trait": openTraitDetail(el.dataset.trait); break;
    }
  }
  function onOverlayInput(e) {
    if (e.target.classList.contains("ovl-search")) { state.ovl.search = e.target.value; refreshOverlay(); return; }
    if (e.target.classList.contains("lv-range") || e.target.classList.contains("lv-num")) {
      let v = Math.max(1, Math.min(99, Number(e.target.value) || 1));
      state.ovl.level = v; refreshOverlay();
    }
  }
  function onDetailClick(e) {
    const el = e.target.closest("[data-action]");
    if (!el) { if (e.target.id === "detail-overlay-root") closeDetail(); return; }
    switch (el.dataset.action) {
      case "close-detail": closeDetail(); break;
      case "nav-class": openClassDetail(el.dataset.class, isEditingContext()); break;
      case "tree-lens": if (!state.treeLockGender) { state.treeLens = el.dataset.lens; openClassDetail(state.detailClass, state.detailEditing); } break;
      case "nav-trait": openTraitDetail(el.dataset.trait); break;
      case "assign-class":
        if (state.ovl && !isLocked()) { state.ovl.classId = el.dataset.class; closeDetail(); refreshOverlay(); }
        break;
    }
  }
  // whether the class detail was opened in an editing context (roster overlay open)
  const isEditingContext = () => {
    const btn = document.querySelector('#detail-overlay-root [data-action="assign-class"]');
    return !!btn || (!!state.ovl && !isLocked());
  };

  // trait detail reuses the detail overlay: show the trait + the classes that carry it
  function openTraitDetail(id) {
    const t = traitById.get(id); if (!t) return;
    const users = (DATA.classes || []).filter((c) => (c.traits || []).includes(id));
    const list = users.length
      ? `<div class="tree-chips">${users.map((c) => chip(c.id, false)).join("")}</div>`
      : `<p class="muted">No classes carry this trait.</p>`;
    const root = document.getElementById("detail-overlay-root");
    root.innerHTML = `
      <div class="overlay-panel detail-panel" role="dialog" aria-modal="true">
        <div class="overlay-header"><h2>${esc(t.name)}</h2><button class="overlay-close" data-action="close-detail">&times;</button></div>
        <div class="overlay-body"><div class="ovl-center"><div class="ovl-center-scroll detail-main">
          <div class="primary-traits">${traitBanner(t)}</div>
          <p>${esc(t.blurb || "")}</p>
          <h3>Classes with this trait (${users.length})</h3>${list}
        </div></div></div>
        <div class="overlay-footer"><button class="ghost" data-action="close-detail">Close</button></div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
  }

  function onKeydown(e) {
    if (e.key !== "Escape") return;
    if (!document.getElementById("detail-overlay-root").classList.contains("hidden")) return closeDetail();
    if (state.ovl) closeOverlay(false);
  }

  // hover a unit → highlight the allied tiles it covers (the "tiles considered covered")
  function highlightCover(el) {
    const stage = document.querySelector(".formation-stage"); if (!stage) return;
    stage.querySelectorAll(".coverer,.cover-target").forEach((n) => n.classList.remove("coverer", "cover-target"));
    if (!el) return;
    const covers = (el.dataset.covers || "").split(",").filter((s) => s !== "");
    if (!covers.length) return;
    el.classList.add("coverer");
    covers.forEach((j) => { const t = stage.querySelector(`.grid-slot[data-slot="${j}"]`); if (t) t.classList.add("cover-target"); });
  }
  function onAppHover(e) {
    const app = document.getElementById("app");
    if (!app.querySelector(".formation-stage")) return;
    highlightCover(e.target.closest(".grid-slot.filled"));
  }

  // ── init ──
  const app = document.getElementById("app");
  app.addEventListener("click", onAppClick);
  app.addEventListener("mouseover", onAppHover);
  app.addEventListener("mouseout", (e) => { if (!e.relatedTarget || !e.relatedTarget.closest(".grid-slot.filled")) highlightCover(null); });
  document.getElementById("overlay-root").addEventListener("click", onOverlayClick);
  document.getElementById("overlay-root").addEventListener("input", onOverlayInput);
  document.getElementById("detail-overlay-root").addEventListener("click", onDetailClick);
  document.addEventListener("keydown", onKeydown);
  normalizeSquad();   // drop any overlapping (within 1 column) units from legacy data before first paint
  renderApp();
})();
