/*
  Symphony of War — Squad Build Calculator (P0 baseline).
  Build-first + overlay-driven. Reads window.SOW_DATA (generated by build-data.mjs).

  The home screen is a 3×5 formation grid (15 slots, leader at slot 0). Clicking a slot
  opens the ROSTER selector overlay; inside it you set the unit's class/level/affinity and
  can open the CLASS UPGRADE TREE (a detail overlay stacked above) to navigate classup/
  classdown edges and analyse requirements, costs, param_add and the stat curve.

  Conventions honoured: statically-sized overlays, scroll-preserving re-renders, event
  delegation on the roots, escape=dismiss / Confirm=commit, traits-as-data banners, and a
  grid stat table with fixed Base | Class Bonus | Total semantics.

  NOTE: stats here are the raw class-table curve + flat param_add — a first-pass sandbox
  metric. The full effective-stat assembly (level variance, affinity growth, "homegrown",
  softcaps, equipment) is a P1 item; see Progress.md.
*/
(function () {
  "use strict";

  const DATA = window.SOW_DATA || {};
  const STORAGE_KEY = "sowbc.squad";
  const SQUAD_SIZE = 15;          // 3 rows × 5 cols
  const COLS = 5;
  const LEADER_SLOT = 0;

  const classById  = new Map((DATA.classes || []).map((c) => [c.id, c]));
  const heroById   = new Map((DATA.heroes || []).map((h) => [h.id, h]));
  const traitById  = new Map((DATA.traits || []).map((t) => [t.id, t]));
  const affById    = new Map((DATA.affinities || []).map((a) => [a.id, a]));
  const STAT_META  = DATA.statMeta || [];
  const PARAM_LABEL = DATA.paramLabel || {};

  // param_add note-tag keys → canonical class-table stat keys (02_stats_scaling.md:
  // def and armor both target the Armor param). Keys not mapped (e.g. agi) are shown raw
  // in the class detail but not folded into the 8-stat table.
  const PARAM_ADD_MAP = { mhp: "HP", atk: "Attack", mat: "Magic", def: "Armor", armor: "Armor", weapon_power: "WeaponPower", skl: "Skill" };
  const RESOURCE_LABEL = { iron: "Iron", obsidian: "Obsidian", gems: "Gems", horse: "Horse", sunstone: "Sunstone", pyrocite: "Pyrocite" };

  // ── state ──
  const state = { squad: load(), ovl: null };

  function makeUnit(hero) {
    return { heroId: hero.id, classId: hero.startClass || null, level: hero.level || 1, affinity: hero.affinity, homegrown: true };
  }
  function load() {
    let arr = [];
    try { arr = JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; } catch { arr = []; }
    return Array.from({ length: SQUAD_SIZE }, (_, i) => (arr[i] && arr[i].heroId ? arr[i] : null));
  }
  function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.squad)); }

  // ── html helpers ──
  const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  function textColorFor(hex) {
    const m = /^#?([0-9a-f]{6})$/i.exec(String(hex || "")); if (!m) return "#fff";
    const n = parseInt(m[1], 16), r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255 > 0.6 ? "#111" : "#fff";
  }
  const affIcon = (id) => { const a = affById.get(id); return a ? a.icon : null; };

  // ── stat math ──
  // Piecewise-linear interpolation of the class table (L1/L20/L50), extrapolated past 50
  // with the per-level growth rate.
  function statAt(cls, key, lvl) {
    const a = Number(cls.statsL1?.[key] || 0), b = Number(cls.statsL20?.[key] || 0), c = Number(cls.statsL50?.[key] || 0);
    if (lvl <= 1) return a;
    if (lvl <= 20) return a + (b - a) * (lvl - 1) / 19;
    if (lvl <= 50) return b + (c - b) * (lvl - 20) / 30;
    return c + (Number(cls.growth?.[key] || 0)) * (lvl - 50);
  }
  function foldParamAdd(cls) {
    const out = {};
    for (const [k, v] of Object.entries(cls.paramAdd || {})) {
      const sk = PARAM_ADD_MAP[k]; if (!sk) continue;
      out[sk] = (out[sk] || 0) + Number(v || 0);
    }
    return out;
  }
  // Full per-stat readout for a class at a level: {base, bonus, total, capped} per stat key.
  function statLines(cls, lvl) {
    const bonus = foldParamAdd(cls);
    const maxBonusAbs = Math.max(0, ...Object.values(bonus).map((v) => Math.abs(v)));
    return STAT_META.map((meta) => {
      const base = Math.round(statAt(cls, meta.key, lvl));
      const add = Math.round(bonus[meta.key] || 0);
      const raw = base + add;
      const capped = meta.cap != null && raw > meta.cap;
      return { meta, base, add, total: capped ? meta.cap : raw, capped, defining: add !== 0 && Math.abs(add) === maxBonusAbs };
    });
  }

  function statTableHTML(cls, lvl) {
    if (!cls) return `<p class="muted">No class stats (off-tree special unit).</p>`;
    const rows = statLines(cls, lvl).map((s) => {
      if (!s.base && !s.add) return "";
      const hl = s.add ? (s.defining ? " hl-high" : " hl-med") : "";
      const cls2 = s.add > 0 ? " pos" : s.add < 0 ? " neg" : "";
      const disp = s.add > 0 ? "+" + s.add : s.add < 0 ? String(s.add) : "—";
      return `<div class="stat-row${hl}${s.capped ? " capped" : ""}">
        <span class="stat-key">${s.meta.icon ? `<img src="${esc(s.meta.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(s.meta.label)}</span>
        <span class="stat-base">${s.base}</span>
        <span class="stat-src stat-val${cls2}">${disp}</span>
        <span class="stat-total">${s.total}</span>
      </div>`;
    }).join("");
    return `<div class="stat-grid">
      <div class="stat-header"><span>Stat</span><span>Base</span><span>Class</span><span>Total</span></div>
      ${rows}</div>`;
  }

  // ── unit helpers ──
  const unitClass = (u) => (u && u.classId ? classById.get(u.classId) : null);
  const unitHero  = (u) => (u ? heroById.get(u.heroId) : null);
  function unitCost(u) { const c = unitClass(u); const raw = c ? Number(c.capacityCost) : 100; return Math.max(1, Math.round((raw || 100) / 10)); }
  function unitStatTotal(u, key) { const c = unitClass(u); if (!c) return 0; const s = statLines(c, u.level).find((x) => x.meta.key === key); return s ? s.total : 0; }

  // ── squad summary (capacity + aggregate power) ──
  function squadSummaryHTML() {
    const placed = state.squad.filter(Boolean);
    if (!placed.length) return `<p class="muted">Click a formation slot to add a unit from the roster.</p>`;
    const leader = state.squad[LEADER_SLOT];
    const leaderLdr = leader ? unitStatTotal(leader, "Leadership") : 0;
    const capacity = Math.max(30, leaderLdr);
    const used = placed.reduce((n, u) => n + unitCost(u), 0);
    const over = used > capacity;
    const pct = Math.min(100, Math.round((used / capacity) * 100));

    const AGG = ["HP", "Attack", "Magic", "Skill", "Armor", "WeaponPower"];
    const rows = AGG.map((key) => {
      const meta = STAT_META.find((m) => m.key === key);
      const total = placed.reduce((n, u) => n + unitStatTotal(u, key), 0);
      return `<div class="stat-row two-col">
        <span class="stat-key">${meta?.icon ? `<img src="${esc(meta.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(meta?.label || key)}</span>
        <span class="stat-total">${total}</span></div>`;
    }).join("");

    return `
      <div class="capacity-bar ${over ? "over" : ""}">
        <div class="cap-track"><div class="cap-fill" style="width:${pct}%"></div></div>
        <div class="cap-label">Capacity <b>${used} / ${capacity}</b> ${over ? '<span class="locked-note">— over capacity!</span>' : ""}
          · leader Leadership <b>${leaderLdr || "—"}</b>${leader ? "" : " (no leader in slot 1)"}</div>
      </div>
      <div class="stat-grid">
        <div class="stat-header two-col" style="grid-template-columns:1fr 62px"><span>Squad power</span><span>Σ</span></div>
        ${rows}
      </div>`;
  }

  // ── trait banners (association channel) ──
  function traitBanner(t) {
    if (!t) return "";
    const color = t.color || "var(--surface2)";
    return `<div class="trait-banner" data-action="nav-trait" data-trait="${esc(t.id)}"
      style="--aff-color:${esc(color)};--aff-text:${textColorFor(color)}" title="${esc(t.name)}">
      ${t.icon ? `<span class="trait-banner-icon"><img src="${esc(t.icon)}" alt="" onerror="this.style.visibility='hidden'"></span>` : ""}
      <span class="trait-banner-label">${esc(t.name)}</span></div>`;
  }
  function classTraitsHTML(cls) {
    if (!cls) return "";
    const ts = (cls.traits || []).map((id) => traitById.get(id)).filter(Boolean);
    return ts.length ? `<div class="primary-traits">${ts.map(traitBanner).join("")}</div>` : "";
  }

  // ── cross-reference matrix (traits × units) ──
  function xrefMatrixHTML() {
    const units = state.squad.map((u, i) => (u && unitClass(u) ? { u, i, cls: unitClass(u), hero: unitHero(u) } : null)).filter(Boolean);
    if (units.length < 1) return "";
    const count = new Map();
    for (const { cls } of units) for (const t of cls.traits || []) count.set(t, (count.get(t) || 0) + 1);
    const cols = [...count.keys()].map((id) => traitById.get(id)).filter(Boolean)
      .sort((a, b) => (count.get(b.id) - count.get(a.id)) || a.name.localeCompare(b.name));
    if (!cols.length) return "";
    const colHead = (t) => `<th class="xref-colhead"><div class="xref-col" data-action="nav-trait" data-trait="${esc(t.id)}"
        style="--aff-color:${esc(t.color)};--aff-text:${textColorFor(t.color)}">
        ${t.icon ? `<img class="xref-col-icon" src="${esc(t.icon)}" alt="" onerror="this.style.visibility='hidden'">` : ""}
        <span class="xref-col-name">${esc(t.name)}</span></div></th>`;
    const rows = units.map(({ cls, hero, i }) => {
      const set = new Set(cls.traits || []);
      const label = `${hero ? hero.name : cls.name} · ${cls.name}`;
      return `<tr><th class="xref-rowhead" data-action="nav-class" data-class="${esc(cls.id)}" title="Slot ${i + 1}">${esc(label)}</th>
        ${cols.map((t) => `<td class="${set.has(t.id) ? "xref-on" : ""}">${set.has(t.id) ? "●" : ""}</td>`).join("")}</tr>`;
    }).join("");
    const shared = `<tr class="xref-shared"><th class="xref-rowhead">Shared</th>
      ${cols.map((t) => { const n = count.get(t.id) || 0; return `<td class="${n >= 2 ? "xref-sh" : ""}">${n}</td>`; }).join("")}</tr>`;
    return `<section class="xref-section">
      <h2>Composition coverage</h2>
      <div class="xref-wrap"><table class="squad-xref">
        <thead><tr><th class="xref-corner"></th>${cols.map(colHead).join("")}</tr></thead>
        <tbody>${rows}${shared}</tbody></table></div>
      <div class="xref-legend"><span><b class="xref-on">●</b> unit has trait</span><span><b class="xref-sh">n</b> shared by n units</span></div>
    </section>`;
  }

  // ═══ BUILD VIEW (home) ═══
  function cellHTML(u, i) {
    const isLeader = i === LEADER_SLOT;
    if (!u) {
      return `<div class="cell ${isLeader ? "leader" : ""}" data-action="open-slot" data-slot="${i}">
        ${isLeader ? '<img class="leader-badge" src="assets/ui/sowleader.png" alt="leader" onerror="this.style.display=\'none\'">' : ""}
        <span class="slot-empty">+ add</span></div>`;
    }
    const hero = unitHero(u), cls = unitClass(u);
    const art = hero?.portrait || cls?.icon || "";
    return `<div class="cell filled ${isLeader ? "leader" : ""}" data-action="open-slot" data-slot="${i}">
      ${isLeader ? '<img class="leader-badge" src="assets/ui/sowleader.png" alt="leader" onerror="this.style.display=\'none\'">' : ""}
      ${art ? `<img class="unit-art" src="${esc(art)}" alt="" onerror="this.style.display='none'">` : ""}
      <span class="unit-name">${esc(hero ? hero.name : "?")}</span>
      <span class="unit-class">${esc(cls ? cls.name : "special")}</span>
      <span class="unit-meta">
        ${affIcon(u.affinity) ? `<img src="${esc(affIcon(u.affinity))}" alt="" onerror="this.style.display='none'">` : ""}
        <span class="unit-lv">L${u.level}</span></span></div>`;
  }
  function renderApp() {
    const app = document.getElementById("app");
    const prevMain = app.querySelector(".planning-main");
    const prevScroll = prevMain ? prevMain.scrollTop : 0;

    let grid = "";
    for (let r = 0; r < SQUAD_SIZE / COLS; r++) {
      grid += `<div class="rowlabel">${["Front", "Middle", "Back"][r] || "Row " + (r + 1)}</div>`;
      for (let c = 0; c < COLS; c++) { const i = r * COLS + c; grid += cellHTML(state.squad[i], i); }
    }

    app.innerHTML = `
      <header class="app-header">
        <div><h1>Symphony of War — Squad Builder</h1><div class="tagline">Formation sandbox · class upgrade-tree analysis</div></div>
        <button class="ghost" data-action="clear">Clear</button>
      </header>
      <main class="planning-main">
        <section class="formation-wrap">
          <h2>Formation</h2>
          <div class="formation-legend"><span>◆ Slot 1 = squad leader (Leadership sets capacity)</span><span>Tap a slot to assign a hero</span></div>
          <div class="formation-grid">${grid}</div>
        </section>
        <section class="squad-summary"><h2>Squad summary</h2>${squadSummaryHTML()}</section>
        ${xrefMatrixHTML()}
      </main>`;

    const newMain = app.querySelector(".planning-main");
    if (newMain) newMain.scrollTop = prevScroll;
  }

  // ═══ ROSTER SELECTOR OVERLAY (#overlay-root) ═══
  function openOverlay(slotIndex) {
    const existing = state.squad[slotIndex];
    state.ovl = existing
      ? { slotIndex, heroId: existing.heroId, classId: existing.classId, level: existing.level, affinity: existing.affinity, homegrown: existing.homegrown, search: "" }
      : { slotIndex, heroId: null, classId: null, level: 1, affinity: null, homegrown: true, search: "" };
    const root = document.getElementById("overlay-root");
    root.innerHTML = `
      <div class="overlay-panel" role="dialog" aria-modal="true">
        <div class="overlay-header">
          <h2>Assign unit — slot ${slotIndex + 1}${slotIndex === LEADER_SLOT ? " (leader)" : ""}</h2>
          <button class="overlay-close" data-action="cancel" aria-label="Close">&times;</button>
        </div>
        <div class="overlay-body">
          <div class="ovl-info"><div class="ovl-left"></div><div class="ovl-right"></div></div>
          <div class="ovl-center">
            <div class="ovl-center-search"><input class="ovl-search" type="search" placeholder="Search heroes…" /></div>
            <div class="ovl-center-scroll"><div class="ovl-grid"></div></div>
          </div>
        </div>
        <div class="overlay-footer">
          ${existing ? '<button class="ghost danger" data-action="remove">Remove unit</button>' : ""}
          <button class="ghost" data-action="cancel">Cancel</button>
          <button data-action="confirm">Confirm</button>
        </div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
    refreshOverlay();
    const input = root.querySelector(".ovl-search"); if (input) input.focus();
  }

  const SCROLLERS = [".ovl-center-scroll", ".ovl-info", ".ovl-left", ".ovl-right-body"];
  function refreshOverlay() {
    const panel = document.querySelector("#overlay-root .overlay-panel");
    if (!panel || !state.ovl) return;
    const saved = SCROLLERS.map((s) => { const el = panel.querySelector(s); return el ? el.scrollTop : 0; });

    const q = state.ovl.search.trim().toLowerCase();
    const heroes = (DATA.heroes || []).filter((h) => !q || h.name.toLowerCase().includes(q));
    panel.querySelector(".ovl-grid").innerHTML = heroes.length ? heroes.map((h) => {
      const cls = h.startClass ? classById.get(h.startClass) : null;
      const art = h.portrait || cls?.icon || "";
      return `<div class="ovl-card ${h.id === state.ovl.heroId ? "selected" : ""}" data-action="pick" data-hero="${esc(h.id)}" title="${esc(h.name)}">
        ${affIcon(h.affinity) ? `<img class="oc-aff" src="${esc(affIcon(h.affinity))}" alt="" onerror="this.style.display='none'">` : ""}
        ${art ? `<img src="${esc(art)}" alt="" onerror="this.style.visibility='hidden'">` : `<span>${esc(h.name[0])}</span>`}
        <span class="oc-name">${esc(h.name)}</span></div>`;
    }).join("") : `<p class="muted">No matching heroes.</p>`;

    const hero = state.ovl.heroId ? heroById.get(state.ovl.heroId) : null;
    const cls = state.ovl.classId ? classById.get(state.ovl.classId) : null;

    // left: the unit's stat table at the chosen level
    panel.querySelector(".ovl-left").innerHTML = `<h3>Stats — L${state.ovl.level}</h3>` +
      (hero ? statTableHTML(cls, state.ovl.level) : `<p class="muted">Pick a hero.</p>`);

    // right: identity + editor controls
    panel.querySelector(".ovl-right").innerHTML = hero ? renderEditor(hero, cls) :
      `<div class="ovl-right-top"><h3>Details</h3></div><div class="ovl-right-body"><p class="muted">Select a hero to configure.</p></div>`;

    SCROLLERS.forEach((s, i) => { const el = panel.querySelector(s); if (el) el.scrollTop = saved[i]; });
  }

  function renderEditor(hero, cls) {
    const innate = (hero.innateTraits || []).map((id) => `<span class="req-chip">${esc(id)}</span>`).join(" ");
    const affChips = (DATA.affinities || []).map((a) => `
      <span class="aff-chip ${a.id === state.ovl.affinity ? "on" : ""}" data-action="set-aff" data-aff="${esc(a.id)}" style="--aff-color:${esc(a.color)}">
        <img src="${esc(a.icon)}" alt="" onerror="this.style.display='none'">${esc(a.name)}</span>`).join("");
    return `
      <div class="ovl-right-top">
        <h3>${esc(hero.name)}</h3>
        <p class="muted">${esc(cls ? cls.name + " · T" + cls.tier : "off-tree special class")}${hero.customTree ? " · custom tree" : ""}</p>
      </div>
      <div class="ovl-right-body">
        ${classTraitsHTML(cls)}
        <div class="editor-row"><label>Level</label>
          <div class="level-control">
            <input type="range" class="lv-range" min="1" max="99" value="${state.ovl.level}">
            <input type="number" class="lv-num" min="1" max="99" value="${state.ovl.level}">
          </div></div>
        <div class="editor-row"><label>Affinity ${hero ? "" : ""}</label><div class="aff-picker">${affChips}</div></div>
        <div class="editor-row"><label>Class</label>
          ${hero.locked
            ? `<span class="locked-note">Class locked (story unit)</span>${cls ? "" : ""}`
            : `<button data-action="open-tree" data-class="${esc(cls ? cls.id : "fighter")}">View / change class tree ▸</button>`}
        </div>
        ${innate ? `<div class="editor-row"><label>Innate traits</label>${innate}</div>` : ""}
        <p class="muted">Affinity is changeable in-game; heroes start with the affinity shown.</p>
      </div>`;
  }

  function closeOverlay(commit) {
    if (!state.ovl) return;
    if (commit && state.ovl.heroId) {
      state.squad[state.ovl.slotIndex] = { heroId: state.ovl.heroId, classId: state.ovl.classId, level: state.ovl.level, affinity: state.ovl.affinity, homegrown: state.ovl.homegrown };
      persist();
    }
    state.ovl = null;
    const root = document.getElementById("overlay-root");
    root.classList.add("hidden"); root.setAttribute("aria-hidden", "true"); root.innerHTML = "";
    renderApp();
  }
  function removeUnit() {
    if (!state.ovl) return;
    state.squad[state.ovl.slotIndex] = null; persist();
    state.ovl = null;
    const root = document.getElementById("overlay-root");
    root.classList.add("hidden"); root.setAttribute("aria-hidden", "true"); root.innerHTML = "";
    renderApp();
  }

  // ═══ CLASS UPGRADE TREE DETAIL (#detail-overlay-root) ═══
  // `editing` = opened from the roster editor, so an "Assign to unit" action is offered.
  function openClassDetail(symbol, editing) {
    const cls = classById.get(symbol); if (!cls) return;
    const root = document.getElementById("detail-overlay-root");
    root.innerHTML = `
      <div class="overlay-panel detail-panel" role="dialog" aria-modal="true">
        <div class="overlay-header">
          <h2>${esc(cls.name)} — upgrade tree</h2>
          <button class="overlay-close" data-action="close-detail" aria-label="Close">&times;</button>
        </div>
        <div class="overlay-body"><div class="ovl-center"><div class="ovl-center-scroll detail-main">${classDetailInner(cls, editing)}</div></div></div>
        <div class="overlay-footer">
          ${editing && !isLocked() ? `<button data-action="assign-class" data-class="${esc(cls.id)}">Assign ${esc(cls.name)} to unit</button>` : ""}
          <button class="ghost" data-action="close-detail">Close</button>
        </div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
    root.querySelector(".detail-main").scrollTop = 0;
  }
  const isLocked = () => { const h = state.ovl && state.ovl.heroId ? heroById.get(state.ovl.heroId) : null; return h ? h.locked : false; };

  function chip(symbol, down) {
    const c = classById.get(symbol); if (!c) return "";
    return `<span class="tree-chip ${down ? "down" : ""}" data-action="nav-class" data-class="${esc(c.id)}">
      ${c.icon ? `<img src="${esc(c.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(c.name)}</span>`;
  }
  function classDetailInner(cls, editing) {
    const req = Object.entries(cls.paramReq || {}).map(([k, v]) => `<span class="req-chip stat">${esc(PARAM_LABEL[k] || "param " + k)} ≥ ${v}</span>`).join(" ") || `<span class="req-none">No stat gate</span>`;
    const cost = Object.entries(cls.resourceCost || {}).map(([k, v]) => `<span class="req-chip">${esc(RESOURCE_LABEL[k] || k)} ×${v}</span>`).join(" ") || `<span class="req-none">Free</span>`;
    const padd = Object.entries(cls.paramAdd || {}).map(([k, v]) => `<span class="req-chip">${esc(k)} ${v > 0 ? "+" : ""}${v}</span>`).join(" ") || `<span class="req-none">None</span>`;
    const up = (cls.classup || []).map((s) => chip(s, false)).join("") || `<span class="req-none">Top of its line</span>`;
    const down = (cls.classdown || []).map((s) => chip(s, true)).join("") || `<span class="req-none">Base class</span>`;

    return `
      <div class="class-head">
        ${cls.icon ? `<img src="${esc(cls.icon)}" alt="" onerror="this.style.display='none'">` : ""}
        <div>
          <span class="ch-tier">Tier ${cls.tier}</span>
          <div class="ch-meta">${esc(cls.archetype.replace(/_/g, " "))} · range ${esc(cls.combatRange)} · mastery ${cls.cxpLimit} CXP · capacity ${Math.max(1, Math.round((cls.capacityCost || 100) / 10))}</div>
          <p>${esc(cls.description || "")}</p>
          ${classTraitsHTML(cls)}
        </div>
      </div>
      <div class="req-block">
        <div class="req-card"><h4>Stat requirement</h4>${req}</div>
        <div class="req-card"><h4>Resource cost</h4>${cost}</div>
        <div class="req-card"><h4>Flat class bonus (param_add)</h4>${padd}</div>
      </div>
      <div class="tree-nav">
        <h4>▲ Upgrades into</h4><div class="tree-chips">${up}</div>
        <h4>▼ Reverts to (class-down)</h4><div class="tree-chips">${down}</div>
      </div>
      <h3>Stat curve (raw class table)</h3>
      ${statCurveHTML(cls)}
      <p class="muted">Requirements assume the source class's mastery bar is full and the tech-tree tier is unlocked. Stats are the raw class-table curve; see Progress.md for the full effective-stat model (P1).</p>`;
  }
  function statCurveHTML(cls) {
    const keys = ["HP", "Attack", "Magic", "Skill", "Armor", "WeaponPower", "Leadership"];
    const rows = keys.map((k) => {
      const meta = STAT_META.find((m) => m.key === k);
      const l1 = Math.round(statAt(cls, k, 1)), l50 = Math.round(statAt(cls, k, 50)), g = (cls.growth?.[k] || 0);
      if (!l1 && !l50 && !g) return "";
      return `<div class="stat-row"><span class="stat-key">${meta?.icon ? `<img src="${esc(meta.icon)}" alt="" onerror="this.style.display='none'">` : ""}${esc(meta?.label || k)}</span>
        <span class="stat-base">${l1}</span><span class="stat-src">${l50}</span><span class="stat-total">${g}/lv</span></div>`;
    }).join("");
    return `<div class="stat-grid"><div class="stat-header"><span>Stat</span><span>L1</span><span>L50</span><span>Growth</span></div>${rows}</div>`;
  }
  function closeDetail() {
    const root = document.getElementById("detail-overlay-root");
    root.classList.add("hidden"); root.setAttribute("aria-hidden", "true"); root.innerHTML = "";
  }

  // ═══ EVENT DELEGATION ═══
  function onAppClick(e) {
    const el = e.target.closest("[data-action]"); if (!el) return;
    switch (el.dataset.action) {
      case "open-slot": openOverlay(Number(el.dataset.slot)); break;
      case "clear": if (state.squad.some(Boolean)) { state.squad = state.squad.map(() => null); persist(); renderApp(); } break;
      case "nav-trait": openTraitDetail(el.dataset.trait); break;
      case "nav-class": openClassDetail(el.dataset.class, false); break;
    }
  }
  function onOverlayClick(e) {
    const el = e.target.closest("[data-action]");
    if (!el) { if (e.target.id === "overlay-root") closeOverlay(false); return; }
    switch (el.dataset.action) {
      case "pick": {
        const id = el.dataset.hero;
        if (state.ovl.heroId === id) { state.ovl.heroId = null; }
        else { const h = heroById.get(id); state.ovl.heroId = id; state.ovl.classId = h.startClass || null; state.ovl.level = h.level || 1; state.ovl.affinity = h.affinity; state.ovl.homegrown = true; }
        refreshOverlay(); break;
      }
      case "set-aff": state.ovl.affinity = el.dataset.aff; refreshOverlay(); break;
      case "open-tree": openClassDetail(el.dataset.class, true); break;
      case "remove": removeUnit(); break;
      case "cancel": closeOverlay(false); break;
      case "confirm": closeOverlay(true); break;
      case "nav-trait": openTraitDetail(el.dataset.trait); break;
    }
  }
  function onOverlayInput(e) {
    if (e.target.classList.contains("ovl-search")) { state.ovl.search = e.target.value; refreshOverlay(); return; }
    if (e.target.classList.contains("lv-range") || e.target.classList.contains("lv-num")) {
      let v = Math.max(1, Math.min(99, Number(e.target.value) || 1));
      state.ovl.level = v; refreshOverlay();
    }
  }
  function onDetailClick(e) {
    const el = e.target.closest("[data-action]");
    if (!el) { if (e.target.id === "detail-overlay-root") closeDetail(); return; }
    switch (el.dataset.action) {
      case "close-detail": closeDetail(); break;
      case "nav-class": openClassDetail(el.dataset.class, isEditingContext()); break;
      case "nav-trait": openTraitDetail(el.dataset.trait); break;
      case "assign-class":
        if (state.ovl && !isLocked()) { state.ovl.classId = el.dataset.class; closeDetail(); refreshOverlay(); }
        break;
    }
  }
  // whether the class detail was opened in an editing context (roster overlay open)
  const isEditingContext = () => {
    const btn = document.querySelector('#detail-overlay-root [data-action="assign-class"]');
    return !!btn || (!!state.ovl && !isLocked());
  };

  // trait detail reuses the detail overlay: show the trait + the classes that carry it
  function openTraitDetail(id) {
    const t = traitById.get(id); if (!t) return;
    const users = (DATA.classes || []).filter((c) => (c.traits || []).includes(id));
    const list = users.length
      ? `<div class="tree-chips">${users.map((c) => chip(c.id, false)).join("")}</div>`
      : `<p class="muted">No classes carry this trait.</p>`;
    const root = document.getElementById("detail-overlay-root");
    root.innerHTML = `
      <div class="overlay-panel detail-panel" role="dialog" aria-modal="true">
        <div class="overlay-header"><h2>${esc(t.name)}</h2><button class="overlay-close" data-action="close-detail">&times;</button></div>
        <div class="overlay-body"><div class="ovl-center"><div class="ovl-center-scroll detail-main">
          <div class="primary-traits">${traitBanner(t)}</div>
          <p>${esc(t.blurb || "")}</p>
          <h3>Classes with this trait (${users.length})</h3>${list}
        </div></div></div>
        <div class="overlay-footer"><button class="ghost" data-action="close-detail">Close</button></div>
      </div>`;
    root.classList.remove("hidden"); root.setAttribute("aria-hidden", "false");
  }

  function onKeydown(e) {
    if (e.key !== "Escape") return;
    if (!document.getElementById("detail-overlay-root").classList.contains("hidden")) return closeDetail();
    if (state.ovl) closeOverlay(false);
  }

  // ── init ──
  document.getElementById("app").addEventListener("click", onAppClick);
  document.getElementById("overlay-root").addEventListener("click", onOverlayClick);
  document.getElementById("overlay-root").addEventListener("input", onOverlayInput);
  document.getElementById("detail-overlay-root").addEventListener("click", onDetailClick);
  document.addEventListener("keydown", onKeydown);
  renderApp();
})();
